import mirrorCreator from 'mirror-creator';

export default mirrorCreator([
  /**Setting shop value actions*/
  'NEW_SHOP_SET_NAME',
  'NEW_SHOP_SET_LOGO',
  'NEW_SHOP_REMOVE_LOGO',
  'NEW_SHOP_SET_BANNER',
  'NEW_SHOP_REMOVE_BANNER',
  'NEW_SHOP_NAME_AVAILABLE',
  'NEW_SHOP_SET_CURRENCY',
  'NEW_SHOP_SET_LANGUAGE',
  'NEW_SHOP_SET_COUNTRY',
  /**Stock modes*/
  'NEW_SHOP_STOCK_ADD_MODE',
  'NEW_SHOP_STOCK_LIST_MODE',
  'NEW_SHOP_STOCK_EDIT_MODE',

  'NEW_SHOP_ADD_ARTICLE',
  'NEW_SHOP_REMOVE_ARTICLE',
  'NEW_SHOP_SET_ARTICLE',

  'NEW_SHOP_SET_CURRENT_PANEL',
  'NEW_SHOP_FETCH_CATEGORIES',
  'NEW_SHOP_FETCH_SUB_CATEGORIES',
  'NEW_SHOP_ARTICLE_SET_NAME',
  'NEW_SHOP_ARTICLE_SET_DESCRIPTION',
  'NEW_SHOP_ARTICLE_SET_PRICE',
  'NEW_SHOP_ARTICLE_SET_MAIN_CATEGORY',
  'NEW_SHOP_ARTICLE_SET_CATEGORY',
  'NEW_SHOP_ARTICLE_SET_SUB_CATEGORY',
  'NEW_SHOP_ARTICLE_CLEAN_ALL',
  'NEW_SHOP_ADD_IMAGE',
  'NEW_SHOP_REMOVE_IMAGE',
  
  //TODO remove
  'NEW_SHOP_UPLOAD_IMAGES',
  
  'NEW_SHOP_CREATE_ARTICLE',
  'NEW_SHOP_CREATE_SHOP'
]);
